kind: uapf.package
id: uapf.demo-process1
name: Order Fulfillment
description: Order fulfillment process
level: 4
version: 0.1.0
includes: []
cornerstones:
  bpmn: true
  dmn: true
  cmmn: true
  resources: true
paths:
  bpmn: bpmn
  dmn: dmn
  cmmn: cmmn
  resources: resources
  metadata: metadata
owners:
  - type: team
    id: "{{.RepoOwner}}"
    contact: "{{.RepoOwner}}@processgit.local"
lifecycle: draft
