kind: uapf.package
id: uapf.single-process
name: Single Process Package
description: A single Level-4 process package template.
level: 4
version: 0.1.0
includes: []
cornerstones:
  bpmn: true
  dmn: true
  cmmn: true
  resources: true
paths:
  bpmn: bpmn
  dmn: dmn
  cmmn: cmmn
  resources: resources
  metadata: metadata
owners:
  - type: team
    id: "{{.RepoOwner}}"
    contact: "{{.RepoOwner}}@processgit.local"
lifecycle: draft
